import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { JACO } from 'use-substrate/dist/src/consts/addresses'
import { useBalances } from 'use-substrate/dist/src/hooks/useBalances'
import { useAccounts } from 'use-substrate/dist/src/hooks/useAccounts'

const Home: NextPage =  () => {
  const balances = useBalances(JACO)
  const accounts = useAccounts()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Statemine
        </h1>

        <p className={styles.description}>
         Balance: {balances?.freeBalance.toString()}
        </p>
        <div>Extension accounts:</div>
        <ul>
          {
            accounts.allAccounts.map((account, index) => <li key={index}>address: {account.address} name: {account.name}</li>)
          }
        </ul>
      </main>
    </div>
  )
}

export default Home
