import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useBalances } from 'use-substrate'
import { ALICE } from 'use-substrate'

const Home: NextPage =  () => {
  const balances = useBalances(ALICE)

  console.log(`freeBalance ${balances?.freeBalance}, availableBalance ${balances?.availableBalance}, accountNonce ${balances?.accountNonce}, lockedBalance ${balances?.lockedBalance}`)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Statemine
        </h1>

        <p className={styles.description}>
         Balance: {balances?.freeBalance.toString()}
        </p>
      </main>
    </div>
  )
}

export default Home
