import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect} from "react"
import {useApi} from "./api/context"
import {useAsync} from "./api/useAsync"
import {DeriveBalancesAll} from "@polkadot/api-derive/types"

const JACO = 'J9nD3s7zssCX7bion1xctAF6xcVexcpy2uwy4jTm9JL8yuK'

function useBalance() {
  const api = useApi()

  return useAsync<DeriveBalancesAll>(() => api.api.derive.balances.all(JACO), [])
}

const Home: NextPage =  () => {
  const balance = 3500
  const {} useBalance()

  console.log(`freeBalance ${freeBalance}, availableBalance ${availableBalance}, accountNonce ${accountNonce}, lockedBalance ${lockedBalance}`)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Statemine
        </h1>

        <p className={styles.description}>
         Balance: {balance}
        </p>
      </main>
    </div>
  )
}

export default Home
