import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import  { ApiPromise, WsProvider } from '@polkadot/api'
import {useEffect} from "react"

const JACO = 'J9nD3s7zssCX7bion1xctAF6xcVexcpy2uwy4jTm9JL8yuK'

function api() {
  async function main () {


    // Retrieve the chain & node information information via rpc calls
    const [chain, nodeName, nodeVersion] = await Promise.all([
      api.rpc.system.chain(),
      api.rpc.system.name(),
      api.rpc.system.version()
    ])

    const { freeBalance, availableBalance, accountNonce, lockedBalance } = await api.derive.balances?.all(JACO)

    console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion}`)
    // console.log(`JACO has ${free} free balance and ${nonce} nonce, reserved: ${reserved}`)
    console.log(`freeBalance ${freeBalance}, availableBalance ${availableBalance}, accountNonce ${accountNonce}, lockedBalance ${lockedBalance}`)
  }

  main().catch(console.error)
}

const Home: NextPage = () => {
  const balance = 3500
  useEffect(() => api(), [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Statemine
        </h1>

        <p className={styles.description}>
         Balance: {balance}
        </p>
      </main>
    </div>
  )
}

export default Home
