name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.18'
      - run: node common/scripts/install-run-rush.js install
      - run: rush build
      - run: rush lint
      - run: rush test
