name: Nightly tests run
on:
  pull_request:
    branches:
      - main
jobs:
  alltests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.18'
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js build
      - run: node common/scripts/install-run-rush.js test:all